### ISSUE TITLE
Unable to create a new Haskell project

### ISSUE THREAD

**Issue by codeguru42** [rikvdkleij/intellij-haskell#250] opened 2018-01-13 12:49 UTC
I just installed this plugin and encountered a problem similar to #208.

Reproduction steps
==

1. File -> New Project...
2. Select Haskell module and Stack binary under Project SDK
3. Click Next
4. Enter Project Name, select Location, and click Finish

Results
==

After a significant amount of time, a dialog box pops up with the following message:

> Could not create Haskell module because could not retrieve or parse Cabal file for package path None

Clicking OK gives another dialog box with this message:

> Error adding module to project: null

Clicking OK produces a bubble which states that IntelliJ encountered an error and the error reporting tool contains the following stacktrace:

> AWT events are not allowed inside write action: sun.awt.PeerEvent[INVOCATION_DEFAULT,runnable=sun.awt.SunToolkit$1@2f05c659,notifier=null,catchExceptions=false,when=1515847202837] on sun.awt.X11.XToolkit@697259d2
java.lang.Throwable: AWT events are not allowed inside write action: sun.awt.PeerEvent[INVOCATION_DEFAULT,runnable=sun.awt.SunToolkit$1@2f05c659,notifier=null,catchExceptions=false,when=1515847202837] on sun.awt.X11.XToolkit@697259d2
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.a(NoSwingUnderWriteAction.java:36)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:377)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.openapi.ui.Messages$MessageDialog.show(Messages.java:1471)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:288)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:300)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:311)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:736)
	at intellij.haskell.module.HaskellModuleBuilder.setupRootModel(HaskellModuleBuilder.scala:78)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:263)
	at intellij.haskell.module.HaskellModuleBuilder.setupModule(HaskellModuleBuilder.scala:115)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createModule(ModuleBuilder.java:256)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:294)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.lambda$commitModule$3(ModuleBuilder.java:337)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1027)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:336)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:322)
	at com.intellij.ide.impl.NewProjectUtil.a(NewProjectUtil.java:149)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:76)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:71)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:36)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:67)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:156)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:80)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:352)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by rikvdkleij** [comment] 2018-01-13 13:19
It looks like a problem with your Stack configuration. Issue #208 was caused by missing template pameters in `~/.stack/config.yaml`.

In master I made changes so it's becomes more clear why Stack is failing to create new Stack project based on template. I can upload that snapshot version to GitHub today so you can try that version.

**Comment by codeguru42** [comment] 2018-01-13 17:48
Here is my `~/.stack/config.yaml`, the default which exists immediately after installing Stack:

	# This file contains default non-project-specific settings for 'stack', used
	# in all projects.  For more information about stack's configuration, see
	# http://docs.haskellstack.org/en/stable/yaml_configuration/

	# The following parameters are used by "stack new" to automatically fill fields
	# in the cabal config. We recommend uncommenting them and filling them out if
	# you intend to use 'stack new'.
	# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
	templates:
	  params:
	#    author-name:
	#    author-email:
	#    copyright:
	#    github-username:

**Comment by codeguru42** [comment] 2018-01-13 18:05
Here is the output from creating a Stack project from the command-line:

	$ stack new --bare hspec
	Downloading template "new-template" to create project "hspec" in the current directory

	The following parameters were needed by the template but not provided: author-email, author-name, category, copyright, github-username
	You can provide them in /home/l/.stack/config.yaml, like this:
	templates:
	  params:
	    author-email: value
	    author-name: value
	    category: value
	    copyright: value
	    github-username: value
	Or you can pass each one as parameters like this:
	stack new hspec new-template -p "author-email:value" -p "author-name:value" -p "category:value" -p "copyright:value" -p "github-username:value"

I was able to open this this project in IntelliJ. If I have to create a new project from the command-line every time, the utility of this plugin decreases. Similarly, requiring a new install to edit configuration files decreases the usefulness of this plugin.

It would be great if this plugin could either gracefully deal with the missing configuration options or provide a way to edit them in the IntelliJ interface. Perhaps you could add fields in the New Project wizard to set any required options.

**Comment by rikvdkleij** [comment] 2018-01-14 12:19
It should not be necessary to create new project from the command-line. The output of `stack new --bare hspec` is informative. It's not because of a failure. Otherwise no IntelliJ user could create new Haskell Stack projects inside IntelliJ.

I suspect the problem is that especially when the first of all Stack commands is executed, it takes some time before it's finished (because it has to download some data/indices). In master I already gave it some time to finish. Also in case of a failure it will show the error message. Because it's in some intermediate state of creating a new IntelliJ project the default way of reporting errors did not work.

> Perhaps you could add fields in the New Project wizard to set any required options.

That's a good idea but as I already said, it's not a obligation to get the Stack project created.

So you pointed out to me that I have to release a new plugin version soon :-) 

FYI, it's a big challenge to create a solid IDE experience for every OS, computer configuration(for example Nix) and project structure for Haskell/GHC and it's evolving ecosystem and changes because of new GHC versions :-) That said. the plugin relies on external Haskell tools, especially Intero, about which I have no control. I create workarounds but some problems are very difficult to handle, for example, the memory leak in ghci/Intero.

**Comment by Sir4ur0n** [comment] 2018-09-27 21:04
Is this issue still valid?

**Comment by huylv** [comment] 2018-10-18 22:48
@Sir4ur0n sadly, yes. The first time after I installed the plugin, I could create project without any issue. Now it doesn't work any more. The only way seems to be having the project created by `stack new` and import into IntelliJ.

**Comment by Sir4ur0n** [comment] 2018-10-28 11:57
@rikvdkleij Actually creating a new project with the plugin seems pretty broken. Just tried on my Windows machine and I get this:
```
Error adding module to project: Could not create new Stack project:  Downloading template "hspec" to create project "new-haskell-project" in the current directory
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- .\

cabal file path <irrelevant>\new-haskell-project\{{name}}.cabal does not match the package name it defines.
Please rename the file to: new-haskell-project.cabal
For more information, see: https://github.com/commercialhaskell/stack/issues/317
```

**Comment by rikvdkleij** [comment] 2018-10-28 12:37
It is broken because stack 1.9.1 broke it.

It's fixed in master by replacing the `hspec` template by the default template Stack documentation is using.

**Closed** 2018-11-17 09:41 UTC
