### ISSUE TITLE
jumping to wrong definition?

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#524] opened 2020-03-03 11:42 UTC
With beta63
1. Using:
    ```
    $ git clone --recursive https://github.com/unisonweb/unison && \
        git -C unison checkout --recurse-submodules b5cae909
    ```
2. I create a new intellij-haskell project for `unison/`, and open `FileCodebase.hs:345`
  ![image](https://user-images.githubusercontent.com/538571/75772214-c8bd4900-5d4b-11ea-8c62-df16f4a935a2.png)
3. I put the cursor on `Branch.sync` and then Navigate -> Goto (Cmd+B)
4. I want it to open `Branch.hs:477`, but it opens `Causal.hs:134` by mistake.

It seems like a regression to be honest, unless something else has changed.

Thanks in advance :)

**Comment by aryairani** [comment] 2020-03-03 11:45
```
$ stack --version
Version 2.1.3 x86_64
```

**Comment by rikvdkleij** [comment] 2020-03-03 20:44
Thanks for reporting! I will take a look soon.

**Comment by aryairani** [comment] 2020-03-03 23:06
I just noticed a simpler example — even within `Branch.hs`, if I find a reference to the type `Raw` (defined in this file), it jumps to the `Raw` in `Causal.hs`; oops :)

**Comment by rikvdkleij** [comment] 2020-03-04 20:26
It's a bug in ghci:
```
21:14	[project-stack-repl-unison-parser-typechecker:lib] Command :loc-at /home/rik/projects/unison/parser-typechecker/src/Unison/Codebase/Branch.hs 202 12 202 14 Raw took + 3 ms

21:14	[project-stack-repl-unison-parser-typechecker:lib] stdout: /home/rik/projects/unison/parser-typechecker/src/Unison/Codebase/Causal.hs:(97,1)-(100,33)
```

**Comment by rikvdkleij** [comment] 2020-03-04 20:35
About your first case:
- When I put the cursor on `Branch` and do ctrl-b it jumps to `Branch` qualifier at line 73. That's okay;
- I have to do some more investigation for `sync`;

**Comment by aryairani** [comment] 2020-03-04 20:40
Yeah. When it's on `sync` and ctrl-b and it doesn't work, sometimes I go back, try again on `Branch`, it takes me to the qualified, then I go to the module name, and ctrl-b again to open `Branch.hs`, and then search for `sync` :(

**Comment by rikvdkleij** [comment] 2020-03-04 20:48
Ok, at least the issue with `Raw` is explained.

**Comment by rikvdkleij** [comment] 2020-03-05 20:15
Can you check beta64?

**Comment by aryairani** [comment] 2020-03-06 11:58
@rikvdkleij I didn't do a fully clean install like when I opened the ticket (please advise), but it looks like the same issue occurs for me in beta64.

**Comment by rikvdkleij** [comment] 2020-03-06 12:33
@aryairani I couldn't reproduce the issue with `sync` on master so that's why I asked  you to check it. Maybe it helps to invalidate the IntelliJ cache.

**Comment by aryairani** [comment] 2020-03-06 14:49
"Invalidate + Restart" didn't help me, but I'm trying now with a new project (waiting for it to build).

**Comment by rikvdkleij** [comment] 2020-03-06 20:29
@aryairani O sorry, I can reproduce your issue with `Branch.sync` I will take a look.

**Comment by aryairani** [comment] 2020-03-08 12:36
Ok great 😅

**Comment by rikvdkleij** [comment] 2020-03-08 17:02
I have found solutions for both cases, so also for the ghci bug, but need some to test those. Also found other cases which can be improved.

**Comment by aryairani** [comment] 2020-03-09 03:00
🍻

**Comment by aryairani** [comment] 2020-03-16 19:32
Not sure if this is the same or different, but I have been bumping into this:
```
$ git clone --recursive https://github.com/unisonweb/unison && \
    git -C unison checkout --recurse-submodules 9b30c712
```
from `UnisonFile.hs:160:70` I try to jump to `Term.dependencies`, but am jumped to `DataDeclaration.dependencies` instead. 😞

**Comment by rikvdkleij** [comment] 2020-03-16 20:23
Thanks! That's another case...

**Comment by aryairani** [comment] 2020-03-16 21:32
Should I create a separate ticket for this, or is it okay to keep adding them here?

**Comment by rikvdkleij** [comment] 2020-03-17 05:29
A separate ticket is not needed.

**Comment by rikvdkleij** [comment] 2020-03-22 20:59
Should be fixed in beta65

**Comment by rikvdkleij** [comment] 2020-04-01 18:05
@aryairani Can this one be closed?

**Comment by rikvdkleij** [comment] 2020-05-24 19:13
Please reopen if still an issue.

**Closed by rikvdkleij** 2020-05-24 19:13 UTC
