### ISSUE TITLE
Rename `New Haskell File` to `Haskell File` in New menu

### ISSUE THREAD

**Issue by bassmake** [rikvdkleij/intellij-haskell#404] opened 2019-03-30 05:19 UTC
`New Haskell file` is not consistent with other selections:
<img width="614" alt="Screenshot 2019-03-30 at 06 17 54" src="https://user-images.githubusercontent.com/1708543/55271822-a7d6b300-52b3-11e9-8e90-b50ce86c2b73.png">

**Comment by rikvdkleij** [comment] 2019-04-01 13:36
Thanks for reporting!

Looks like a regression issue. Should be `Haskell module`.

**Comment by rikvdkleij** [comment] 2019-04-15 19:39
Should be solved in beta46.

**Comment by Sir4ur0n** [comment] 2019-04-24 11:38
I confirm it's fixed, I guess we can close this.

**Comment by rikvdkleij** [comment] 2019-04-24 18:06
@Sir4ur0n  Thanks!

**Closed by rikvdkleij** 2019-04-24 18:06 UTC
