### ISSUE TITLE
Fast initiation of renaming misses all other occurrences

### ISSUE THREAD

**Issue by letmaik** [rikvdkleij/intellij-haskell#385] opened 2019-02-13 18:05 UTC
When I click on an identifier and very quickly (via keyboard shortcut) initiate the renaming, then it may happen that the other occurrences are not highlighted/detected yet and it will only rename the identifier under the cursor. This leaves the file in an inconsistent state.

**Comment by rikvdkleij** [comment] 2019-02-14 11:34
Thanks for reporting!

I also sometimes experience that problem, especially when Haskell module is large.

Loading the module takes some times in the REPL and during that loading the REPL is not available for  other requests like asking for location info of a identifier.

Can not do much about that. Plugin tries to cache as much as possible (but can take a look again). Final solution is to use Haskell backend which can handle concurrent requests.

**Comment by letmaik** [comment] 2019-02-14 14:35
Isn't there a way to delay the start of the renaming action so that it waits until the REPL is ready and gave an answer?

**Comment by rikvdkleij** [comment] 2019-02-14 15:26
Just noticed that there is already a simple check if REPL is not busy before renaming. But  it also has to check that all needed references are already known.  But how does IntelliJ know that 😄

Will think about a solution. Maybe some preloading of definition location info...

**Comment by rikvdkleij** [comment] 2019-02-19 15:40
I think I found the cause of this issue. Also for #384 

When the fix is okay then is should  be fixed in next beta.

**Comment by rikvdkleij** [comment] 2019-05-22 13:19
Please reopen when it's still an issue.

**Closed by rikvdkleij** 2019-05-22 13:19 UTC
