### ISSUE TITLE
UI becomes unresponsive

### ISSUE THREAD

**Issue by aryairani** [rikvdkleij/intellij-haskell#280] opened 2018-06-15 16:16 UTC
I know this is a hard one to diagnose, but I'll do my best to help you help me ;-)

I'll attach screenshots including the Event Log at the moment of hanging.

<img width="2048" alt="screen shot 2018-06-15 at 12 13 40 pm" src="https://user-images.githubusercontent.com/538571/41478474-c705d82e-7095-11e8-9c83-2c29056b4792.png">
beta15

**Comment by aryairani** [comment] 2018-06-15 16:20
<img width="1314" alt="screen shot 2018-06-15 at 12 19 43 pm" src="https://user-images.githubusercontent.com/538571/41478619-6c5d6436-7096-11e8-8ee2-da5d2a56d425.png">
Here I believe I had just pressed "Return" to add a line break.

**Comment by rikvdkleij** [comment] 2018-06-15 16:53
Yeah, I also noticed this kind of problems during testing. I have fixed them. I will release new beta soon.

**Comment by rikvdkleij** [comment] 2018-06-16 19:04
You can try beta 16: https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta16

I'm curious to your experience because I do not notice any problems anymore....

**Comment by aryairani** [comment] 2018-06-16 21:04
Thanks, I will install it and keep you posted!

**Comment by aryairani** [comment] 2018-07-04 16:37
I have been using beta17, and while I haven't seen it become unresponsive to the point where I'd have to force quit IntelliJ IDEA, there are often long pauses during text editing and text navigation that make the experience borderline impossible.  Any suggestions?

Thanks!

**Comment by aryairani** [comment] 2018-07-04 16:41
The hangs are sometimes for 10+ seconds at a time, which is enough time to forget what you were trying to do :-(

**Comment by rikvdkleij** [comment] 2018-07-05 08:30
That is a pity. I understand it makes the plugin useless.
 
Suddenly I also experienced this behavior after it was working for a long time very smooth.  I think I know the cause and will have to rewrite some code. 

Normally IntelliJ generates thread dumps when it's not responsive for a while. Do you want to send me those files (to be sure I have experienced the same problem)? On a mac they should be in a folder like `~/Library/Logs/IntelliJIdea2018.1`

**Comment by rikvdkleij** [comment] 2018-07-12 19:43
Responsiveness should be much better in beta18.

**Comment by rikvdkleij** [comment] 2018-07-25 18:16
It looks that I finally found _your_ issue. I could not reproduce it on my Macbook but on my more recent work Macbook I could experience the UI freezing issue.

It's fixed in beta21 which I just released.

**Comment by aryairani** [comment] 2018-07-25 18:59
Thanks Rik, I will give it a shot!

**Comment by rikvdkleij** [comment] 2018-07-26 10:57
Do not know if you are already tried latest beta but I still notice UI responsiveness issues 😞 

So for me still some work todo......

**Comment by rikvdkleij** [comment] 2018-07-29 12:00
Do not know if you are still interested but I released beta22. I do not notice any responsiveness issues anymore.

**Comment by aryairani** [comment] 2018-07-29 12:14
I'm still interested.  My coworkers make fun of me when IntelliJ becomes sluggish or unresponsive, but we'll show them!  😉

**Comment by aryairani** [comment] 2018-07-31 15:29
Today I was able to run it for about 90 minutes before the UI became unresponsive, a new record for me :)  I normally don't run with the Event Log open, because it takes up a lot of real estate on my small display; are there some logs I can get from disk that would be useful to you?

**Comment by rikvdkleij** [comment] 2018-07-31 15:42
Great to hear that there is some progress 😄 

I assume you are using the latest beta, beta22. In master I have done again some changes to improve the UI responsiveness. My plan is to release new beta soon.

> normally don't run with the Event Log open, because it takes up a lot of real estate on my small display; 

The Event log does not help is this issue.

On a Mac you can take a look in the folder  `~/Library/Logs/IntelliJIdea2018.1` to see if there are thread dumps (or change IntelliJ version).

You can also add this 
`
-Ddump.threads.on.long.write.action.waiting=50
`
as JVM argument to IntelliJ and then IntelliJ will dump all threads when it has to wait for a write action for longer than 50 ms.

**Comment by aryairani** [comment] 2018-07-31 16:33
[threadDumps-freeze-20180731-112527-IC-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2246227/threadDumps-freeze-20180731-112527-IC-182.3684.101.zip)
[threadDumps-freeze-20180731-123130-IC-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2246228/threadDumps-freeze-20180731-123130-IC-182.3684.101.zip)

Here are two thread dumps from two different hangs today (beta22)

**Comment by aryairani** [comment] 2018-07-31 16:37
And another 😞 
[threadDumps-freeze-20180731-123556-IC-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2246247/threadDumps-freeze-20180731-123556-IC-182.3684.101.zip)

Keep up the good work! 😄

**Comment by rikvdkleij** [comment] 2018-08-06 18:32
@alexjbush Thanks! Should be solved in next beta.

**Comment by rikvdkleij** [comment] 2018-08-16 18:54
Just released beta23 which contains (again) many improvements.

I'm curious if this beta solves your issues.

**Comment by aryairani** [comment] 2018-08-17 00:30
Thanks! I'll keep you posted and send any new threadDumps.

**Comment by aryairani** [comment] 2018-08-17 13:43
I ran into a couple pretty quickly, let me know if these are helpful at all?
[threadDumps-freeze-20180817-094231-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2297401/threadDumps-freeze-20180817-094231-IU-182.3684.101.zip)

**Comment by rikvdkleij** [comment] 2018-08-17 13:51
That is surprising. For me the plugin is working smoothly.

From your thread dumps it's not yet clear what is going on so more thread dumps will help to solve this issue.

**Comment by aryairani** [comment] 2018-08-17 13:57
Okay, I will keep trying!

**Comment by rikvdkleij** [comment] 2018-08-17 14:00
Great!

I also wonder, is the plugin working smoothly in general except for that one freeze?

**Comment by aryairani** [comment] 2018-08-17 14:07
So far it has frozen for me within a few minutes of opening IntelliJ, so I haven't had any chance to evaluate the plugin otherwise.  Here's another dump; for some reason it was broken into 3 folders.  The status bar said it was building lint the last time it was frozen.  I wonder if I need to just wait and not use the editor at all while the plugin does its initial import/build work?

[threadDumps-freeze-20180817-100312-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2297506/threadDumps-freeze-20180817-100312-IU-182.3684.101.zip)
[threadDumps-freeze-20180817-100149-IU-182.3684.101-13sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/2297507/threadDumps-freeze-20180817-100149-IU-182.3684.101-13sec.zip)
[threadDumps-freeze-20180817-100201-IU-182.3684.101-20sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/2297508/threadDumps-freeze-20180817-100201-IU-182.3684.101-20sec.zip)

**Comment by rikvdkleij** [comment] 2018-08-17 14:10
>  I wonder if I need to just wait and not use the editor at all while the plugin does its initial import/build work?

No, IntelliJ should just work but without the Haskell features which are not ready yet (in this case HLint)

Thanks!

**Comment by aryairani** [comment] 2018-08-17 14:45
[threadDumps-freeze-20180817-104047-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2297647/threadDumps-freeze-20180817-104047-IU-182.3684.101.zip)
Here's a new one.  The editor was idle, and I don't think I got as far as editing anything.

**Comment by aryairani** [comment] 2018-08-17 14:50
(I don't mean it crashed without any interaction, I mean I was probably navigating within a file to find a spot I wanted to edit, but didn't get to do any editing.)

**Comment by rikvdkleij** [comment] 2018-08-17 15:11
Ok, thanks again!!

**Comment by aryairani** [comment] 2018-08-17 17:00
For this one, I opened up IntelliJ, which opened my project.  Then I used Symbol Search to find Data.Monoid.First.  I searched for `First` and was browsing the file when it froze.

[threadDumps-freeze-20180817-125730-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2298077/threadDumps-freeze-20180817-125730-IU-182.3684.101.zip)

Thanks!

**Comment by rikvdkleij** [comment] 2018-08-17 17:49
Do you still use Unison project?

**Comment by aryairani** [comment] 2018-08-17 19:05
Yes, that's the one.

**Comment by rikvdkleij** [comment] 2018-08-18 09:03
Released beta24 and tested with Unison project.

Can you give it another try?

**Comment by aryairani** [comment] 2018-08-19 00:06
Another dump: 
[threadDumps-freeze-20180818-200517-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/2299948/threadDumps-freeze-20180818-200517-IU-182.3684.101.zip)

**Comment by rikvdkleij** [comment] 2018-08-19 16:35
Thanks again! 

Problem is more clear but it's difficult to solve without make compromises. I'm trying different solutions and see which is best.

**Comment by rikvdkleij** [comment] 2018-08-20 08:09
Btw, I can only reproduce unresponsiveness when I use `Find Usages` (which takes some while), put it in the background and start to code. 
Is that also in your case?

**Comment by rikvdkleij** [comment] 2018-08-20 19:02
Released beta 25. Hopefully this one helps 😄

**Comment by aryairani** [comment] 2018-08-20 23:31
>Btw, I can only reproduce unresponsiveness when I use Find Usages (which takes some while), put it in the background and start to code.
Is that also in your case?

No, it definitely hasn't required backgrounding a Find Usages window.  I can't be sure that I didn't Cmd-click to navigate to the definition of some symbol, but I will try to notice.

It usually happens abruptly, not when I have chosen some menu option but when I am navigating in preparation for doing something.  In past iterations, it would also sometimes hang while I was typing, leaving some changes saved and a few keystrokes lost.  In those cases, I just kill IntelliJ and switch to Atom until the next release of the plugin. ;-)

I'll let you know how it goes with beta25, thanks!

**Comment by rikvdkleij** [comment] 2018-08-21 07:58
Thanks! I'm curious if beta25 helps.

In your last dump I see the same issue.

Are you using the bundled JDK from Jetbrains?

**Comment by rikvdkleij** [comment] 2018-08-21 09:03
Okay, I already found a freezing issue myself with beta25....

**Comment by alexjbush** [comment] 2018-08-24 18:56
I've been using beta25 for several hours today with no freezing at all. Previously, it would have frozen several times. This seems likely to have been fixed for me! Thank you @rikvdkleij

**Comment by rikvdkleij** [comment] 2018-08-28 07:56
@alexjbush Great that is fixed for you! 

But I experienced problems with beta25. In the meantime I have (hopefully) fixed that (together with other issues) and will test changes for a couple of days before I release a new beta.

**Comment by aryairani** [comment] 2018-08-28 16:38
New one today with beta25 :(
[threadDumps-freeze-20180828-123351-IC-181.4203.550.zip](https://github.com/rikvdkleij/intellij-haskell/files/2328947/threadDumps-freeze-20180828-123351-IC-181.4203.550.zip)

**Comment by rikvdkleij** [comment] 2018-08-28 18:21
@aryairani Thanks! Yes, I also have experienced freezes with beta25. Changed a lot in the meantime and I'm busy with testing. I hope to release new beta soon.

**Comment by rikvdkleij** [comment] 2018-09-09 12:00
@aryairani Released beta26 which should have a much better responsiveness :smile:

**Comment by rikvdkleij** [comment] 2018-10-02 04:46
@aryairani Yesterday I released beta28. Did you already used the plugin since beta26?

**Comment by aryairani** [comment] 2018-10-15 14:14
I tried beta28 and it didn't hang, but my coworker made fun of me due to the high latency in the editor.

**Comment by rikvdkleij** [comment] 2018-10-15 14:30
Thanks for trying 😄 

I did not notice that but beta29 should be better (beta28 has some problems with loading the cache).

I keep improving 😄

**Comment by rikvdkleij** [comment] 2019-01-03 10:58
@aryairani If you still want to use the plugin, you give beta39 a try.

**Comment by aryairani** [comment] 2019-05-22 13:09
[threadDumps-freeze-20190520-095952-IC-191.7141.44.zip](https://github.com/rikvdkleij/intellij-haskell/files/3207482/threadDumps-freeze-20190520-095952-IC-191.7141.44.zip)

:)

**Comment by rikvdkleij** [comment] 2019-05-22 13:17
@aryairani  Thanks!

Are you using the latest version of plugin?

**Comment by aryairani** [comment] 2019-05-22 22:35
This last one is from beta46 if I'm not mistaken!

**Comment by aryairani** [comment] 2019-05-23 14:35
[threadDumps-freeze-20190523-102829-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/3212697/threadDumps-freeze-20190523-102829-IU-182.3684.101.zip)

This one is for a different type of hang, if I'm not mistaken.  I wasn't really doing anything but browsing files while waiting for intero, etc to build.

**Comment by aryairani** [comment] 2019-05-23 14:39
Hm  I seem to be getting a repeating issue; I uncomment line 270 of Actions2.hs and the UI becomes unresponsive.  Not sure if coincidence, but that's what I had done just before the last 3 hangs in a row.

The first threadDumps is above, the second and third are below.

[threadDumps-freeze-20190523-103559-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/3212719/threadDumps-freeze-20190523-103559-IU-182.3684.101.zip)
[threadDumps-freeze-20190523-103712-IU-182.3684.101.zip](https://github.com/rikvdkleij/intellij-haskell/files/3212720/threadDumps-freeze-20190523-103712-IU-182.3684.101.zip)

**Comment by rikvdkleij** [comment] 2019-05-23 14:58
Thanks again!

Will try to reproduce it but I can also remember that I could only reproduce your issues on a recent MacBook Pro.

**Comment by rikvdkleij** [comment] 2019-05-23 15:47
The freeze of 20-5 was during project closing. The cause is clear.

**Comment by aryairani** [comment] 2019-05-23 19:06
Fwiw, the 20190523 zips are on my 2012 iMac.

**Comment by rikvdkleij** [comment] 2019-06-03 12:37
You can try beta47.

**Comment by rikvdkleij** [comment] 2019-06-03 12:45
Btw, did some quick tests with Unison project and works fine for me.

**Comment by aryairani** [comment] 2019-06-03 18:38
This is with beta47, was trying to use using Option-Enter to resolve a missing import at the time of the hang.

[threadDumps-freeze-20190603-143559-IC-191.7141.44-71sec.zip](https://github.com/rikvdkleij/intellij-haskell/files/3248977/threadDumps-freeze-20190603-143559-IC-191.7141.44-71sec.zip)

Thanks!

**Comment by rikvdkleij** [comment] 2019-06-03 20:09
Thanks for reporting!

I think I found the cause....

**Comment by rikvdkleij** [comment] 2019-06-04 12:54
Released beta48. Also contains fix for intention action to add import which issue I found while testing with Unison.

**Comment by aryairani** [comment] 2019-06-04 14:28
Got it!

**Comment by rikvdkleij** [comment] 2019-06-04 17:27
Ok, I'm curious how it works out for you!

**Comment by aryairani** [comment] 2019-06-06 16:00
Good morning!  This is with beta48 :)

[threadDumps-freeze-20190606-115823-IC-191.7141.44.zip](https://github.com/rikvdkleij/intellij-haskell/files/3262416/threadDumps-freeze-20190606-115823-IC-191.7141.44.zip)

**Comment by rikvdkleij** [comment] 2019-06-06 18:08
Good evening! :smile: 

Well, I do not know what happened but this thread dump does not relate to the Haskell plugin. It can also in happen in general that a write action has to wait longer than 50 ms.

**Comment by aryairani** [comment] 2019-06-06 19:10
Oops, okay :)

**Comment by aryairani** [comment] 2019-07-04 23:30
[threadDumps-freeze-20190704-192651-IC-191.7141.44.zip](https://github.com/rikvdkleij/intellij-haskell/files/3360646/threadDumps-freeze-20190704-192651-IC-191.7141.44.zip)

If I had to guess, this one might have been related to Stylish-Haskell?

**Comment by rikvdkleij** [comment] 2019-07-07 17:32
Thanks for reporting!

In the thread dumps I see nothing that relates to a problem with the plugin.

**Comment by aryairani** [comment] 2019-07-07 18:00
Sorry, thanks for taking a look

**Comment by rikvdkleij** [comment] 2019-09-01 19:41
@aryairani Well, I guess this issue can be closed now. Otherwise please reopen.

**Closed by rikvdkleij** 2019-09-01 19:41 UTC
