### ISSUE TITLE
Joining a line-comment with a next line changes comment to block

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#189] opened 2017-05-27 10:22 UTC
**Actual behavior:**
When pressing "join lines" key combination (Ctrl + Shift + J) line comment changes to block:

![joinlines2](https://cloud.githubusercontent.com/assets/1009751/26520630/c7fbf44a-42d6-11e7-9ea6-c5a20ddc3894.gif)

**Desired behavior:**
Line-comment doesn't change its type, next line is appended and also becomes a comment.

**Comment by rikvdkleij** [comment] 2017-06-02 11:51
This is duplicate of #181

**Closed** 2017-06-02 12:03 UTC
