### ISSUE TITLE
java.lang.AssertionError: Unexpected element type: BOOL_LIT

### ISSUE THREAD

**Issue by jereksel** [rikvdkleij/intellij-haskell#294] opened 2018-08-18 17:53 UTC
To reproduce:
Clone ~~xmonad (https://github.com/xmonad/xmonad)~~ xmonad-contrib (https://github.com/xmonad/xmonad-contrib) and try importing.

Full stacktrace:
```
java.lang.AssertionError: Unexpected element type: BOOL_LIT
	at intellij.haskell.cabal.lang.psi.CabalElementFactory$.createElement(CabalElementFactory.scala:117)
	at intellij.haskell.cabal.lang.psi.CabalElementFactory.createElement(CabalElementFactory.scala)
	at intellij.haskell.cabal.lang.parser.CabalParserDefinition.createElement(CabalParserDefinition.java:64)
	at com.intellij.psi.impl.source.tree.CompositeElement.createPsiNoLock(CompositeElement.java:739)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:726)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:30)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:51)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:100)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:49)
	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:31)
	at com.intellij.util.WalkingState.next(WalkingState.java:73)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at com.intellij.psi.util.PsiTreeUtil$4.visitElement(PsiTreeUtil.java:883)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitFile(PsiRecursiveElementWalkingVisitor.java:70)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:878)
	at com.intellij.psi.util.PsiTreeUtil.findChildrenOfAnyType(PsiTreeUtil.java:334)
	at com.intellij.psi.util.PsiTreeUtil.collectElementsOfType(PsiTreeUtil.java:862)
	at intellij.haskell.psi.HaskellPsiUtil$.streamChildren(HaskellPsiUtil.scala:226)
	at intellij.haskell.cabal.CabalInfo.executables$lzycompute(CabalInfo.scala:68)
	at intellij.haskell.cabal.CabalInfo.executables(CabalInfo.scala:67)
	at intellij.haskell.cabal.CabalInfo.sourceRoots$lzycompute(CabalInfo.scala:89)
	at intellij.haskell.cabal.CabalInfo.sourceRoots(CabalInfo.scala:89)
	at intellij.haskell.module.HaskellModuleBuilder$.addSourceFolders(HaskellModuleBuilder.scala:162)
	at intellij.haskell.module.HaskellModuleBuilder.setupRootModel(HaskellModuleBuilder.scala:83)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.setupModule(ModuleBuilder.java:249)
	at intellij.haskell.module.HaskellModuleBuilder.createModule(HaskellModuleBuilder.scala:116)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.createAndCommitIfNeeded(ModuleBuilder.java:280)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.lambda$commitModule$3(ModuleBuilder.java:323)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1062)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commitModule(ModuleBuilder.java:322)
	at com.intellij.platform.templates.TemplateModuleBuilder.commitModule(TemplateModuleBuilder.java:127)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.commit(ModuleBuilder.java:308)
	at com.intellij.ide.util.projectWizard.ProjectBuilder.commit(ProjectBuilder.java:42)
	at intellij.haskell.module.StackProjectImportBuilder.$anonfun$commit$2(StackProjectImportBuilder.scala:66)
	at intellij.haskell.module.StackProjectImportBuilder.$anonfun$commit$2$adapted(StackProjectImportBuilder.scala:58)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at intellij.haskell.module.StackProjectImportBuilder.commit(StackProjectImportBuilder.scala:58)
	at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:60)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:138)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:60)
	at com.intellij.ide.actions.ImportModuleAction.doCreateFromWizard(ImportModuleAction.java:94)
	at com.intellij.ide.actions.ImportModuleAction.lambda$createFromWizard$0(ImportModuleAction.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.ide.actions.ImportModuleAction.createFromWizard(ImportModuleAction.java:88)
	at com.intellij.ide.actions.ImportModuleAction.doImport(ImportModuleAction.java:83)
	at com.intellij.ide.actions.ImportProjectAction.lambda$actionPerformed$0(ImportProjectAction.java:30)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by rikvdkleij** [comment] 2018-08-18 19:34
Thanks for reporting!

**Comment by Sir4ur0n** [comment] 2018-09-03 20:54
@jereksel Have you tried with an up-to-date Intellij and the latest beta (25) of Intellij Haskell plugin? When I imported (on Windows) it imports correctly.

Intellij: 2018.2.2 (182.4129.33)
Intellij Haskell plugin: Beta 25

**Comment by jereksel** [comment] 2018-09-05 21:25
@Sir4ur0n Yeah, with Beta 25 it imports just fine.

**Comment by jereksel** [comment] 2018-09-05 21:31
Now I've got the same error with [xmonad-contrib](https://github.com/xmonad/xmonad-contrib)

**Comment by rikvdkleij** [comment] 2019-05-22 13:39
Please reopen when it's still an issue.

**Comment by romatthe** [comment] 2019-07-06 23:44
I know this is an old issue, but I'm having the exact same issue, also while trying to edit my Xmonad configuration through Intellij-Haskell. The stack trace seems to be the exact same one as jereksel had over a year ago with beta-25.

This looks like a very reproducible issue.

I'm using
Intellij Community 2019.1.3
Intellij-Haskell: beta-51

**Comment by rikvdkleij** [comment] 2019-07-07 17:58
It's fixed in next beta.

Notice that the `xmonad-contrib` project is using LTS 7 which is not supported (anymore). Only GHC 8.2 and later is supported.

**Comment by rikvdkleij** [comment] 2020-05-24 19:34
Please reopen if still an issue.

**Closed by rikvdkleij** 2020-05-24 19:34 UTC
