### ISSUE TITLE
Stack repl crashes when I have a Paths_<pkg-name> module

### ISSUE THREAD

**Issue by diogob** [rikvdkleij/intellij-haskell#62] opened 2016-11-22 15:10 UTC
Whenever I have a line like: `import Paths_<module_name>` in my source code the load of any dependent source file in intellij-haskell will fail.

One example project where I find this issue is https://github.com/diogob/pg-recorder

An example output from the console:
```
10:05 AM	[project-stack-repl] errOut: 
				/Users/diogobiazus/src/hevent-shovel/src/HeventShovel/Config.hs:15:1: error:
				Failed to load interface for ‘Paths_hevent_shovel’
				Use -v to see a list of the files searched for.

10:05 AM	Error in file `/Users/diogobiazus/src/hevent-shovel/src/HeventShovel/Config.hs`:  error:
				    Failed to load interface for ‘Paths_hevent_shovel’
				    Use -v to see a list of the files searched for.
```

**Comment by zjhmale** [comment] 2016-11-22 16:00
@diogob do you mean this [line](https://github.com/diogob/pg-recorder/blob/master/src/PgRecorder/Config.hs#L13) will cause this error?

**Comment by diogob** [comment] 2016-11-23 01:51
@zjhmale yes, if you run a `stack build` everything works fine, but the way the plugin is compiling aparently never generates this module. The problem is probably related to the fact that this module is dynamically generated by cabal as described in the [cabal user guide](https://www.haskell.org/cabal/users-guide/developing-packages.html#accessing-data-files-from-package-code).

**Comment by zjhmale** [comment] 2016-11-23 02:49
Hi @diogob, I had some trouble with building your `pg_recorder` project, so I imported a generated module [here](https://github.com/zjhmale/HAS/blob/master/spock-todo/app/Main.hs#L7) and loaded in `intellij-haskell` and it worked fine for me.

```
上午10:38:56 [project-stack-repl] command: :load Paths_spock_todo
上午10:38:56 [project-stack-repl] stdOut: [1 of 1] Compiling Paths_spock_todo ( /Users/zjh/Documents/haskellspace/haskell-api-server/spock-todo/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/autogen/Paths_spock_todo.hs, interpreted )
           Ok, modules loaded: Paths_spock_todo.
           Collecting type info for 1 module(s) ... 
           ^IntellijHaskell^
上午10:38:56 [project-stack-repl] errOut: 
上午10:38:56 [project-stack-repl] command: :browse! Paths_spock_todo
上午10:38:56 [project-stack-repl] stdOut: -- defined locally
           version :: Version
           getBinDir :: IO FilePath
           getLibDir :: IO FilePath
           getDataDir :: IO FilePath
           getLibexecDir :: IO FilePath
           getSysconfDir :: IO FilePath
           getDataFileName :: FilePath -> IO FilePath
```

**Comment by zjhmale** [comment] 2016-11-23 04:08
```
下午12:06:00 [project-stack-repl] command: :load Paths_pg_recorder
下午12:06:00 [project-stack-repl] stdOut: [1 of 1] Compiling Paths_pg_recorder ( /Users/zjh/Documents/haskellspace/pg-recorder/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/autogen/Paths_pg_recorder.hs, interpreted )
           Ok, modules loaded: Paths_pg_recorder.
           Collecting type info for 1 module(s) ... 
           ^IntellijHaskell^
下午12:06:00 [project-stack-repl] errOut: 
下午12:06:00 [project-stack-repl] command: :browse! Paths_pg_recorder
下午12:06:00 [project-stack-repl] stdOut: -- defined locally
           version :: Version
           getBinDir :: IO FilePath
           getLibDir :: IO FilePath
           getDataDir :: IO FilePath
           getLibexecDir :: IO FilePath
           getSysconfDir :: IO FilePath
           getDataFileName :: FilePath -> IO FilePath
```

**Comment by diogob** [comment] 2016-11-23 18:10
Hi @zjhmale , first thanks for taking the time to compile my project and troubleshoot this.
I've doubled checked my environment and I still reproduce the error.
My `stack --version` output is:

    Version 1.1.2 x86_64 hpack-0.14.0

My OS is a Mac OS X 10.11

The ItelliJ environment is:
IntelliJ IDEA 2016.2.5
Build #IC-162.2228.15, built on October 14, 2016
JRE: 1.8.0_112-release-287-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o


I also search for any occurrence of the string `Compiling Paths_pg_recorder` within my logs and could not find any.

**Comment by rikvdkleij** [comment] 2016-11-23 19:21
Cause is that Stack repl is started with: `no-load`. I added this option to accelerate starting the repl. I think I can remove this option without problems.

Btw, I advice you to upgrade Stack.

**Comment by diogob** [comment] 2016-11-23 20:02
thanks @rikvdkleij 
I'll test with the changes and the latest stack as soon as I can :D

**Comment by rikvdkleij** [comment] 2016-11-24 11:57
Hmm, problem is more complicated. I now recollect the real reason why I added option `--no-load`. It's because Stack repl will otherwise ask which target to load if I also also pass option `--test`.

I have to investigate how I solve this issue in solid way.

**Comment by rikvdkleij** [comment] 2016-11-24 13:55
I consider to always load `Paths_<package_name>` while starting the Stack repl. I will extract package name from name of Cabal file.

**Comment by rikvdkleij** [comment] 2016-12-27 12:11
Fixed in beta 4.

**Comment by rikvdkleij** [comment] 2017-01-13 20:32
@diogob Can this issue be closed?

**Comment by diogob** [comment] 2017-01-14 00:45
@rikvdkleij sorry for taking so long to update. I was still experiencing the problem using the same setup. But I can double check as soon as I'm back home (I'm out on vacations with spotty connectivity)

**Comment by diogob** [comment] 2017-01-14 00:45
I'll close or update with further info as soon as I can.

**Comment by rikvdkleij** [comment] 2017-02-09 12:35
I can not reproduce this issue with your project `pg-recorder` in beta6. So it's fixed :smile:

**Closed by rikvdkleij** 2017-02-09 12:35 UTC

**Comment by diogob** [comment] 2017-02-09 14:56
Thanks @rikvdkleij 👍
