### ISSUE TITLE
plugin hangs when trying to create a haskell run config

### ISSUE THREAD

**Issue by yunti** [rikvdkleij/intellij-haskell#360] opened 2018-12-14 12:05 UTC
plugin v1.0.0-beta36
intellij ultimate 2018.3.1
macOS 10.14.1

Currently when I setup a new project and try to add a haskell run configuration, the IDE just hangs and I can't add one.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/1826271/50002608-8964da00-ff98-11e8-9870-bcca40012a2d.png">

**Comment by ice1000** [comment] 2018-12-15 04:10
Duplicate of #354 , please try the distribution compiled by me, uploaded in #358

**Comment by rikvdkleij** [comment] 2018-12-16 16:07
@yunti Can you try beta37?

**Comment by yunti** [comment] 2018-12-17 09:38
Thanks and sorry for the duplicate post issue.  I can't see beta37 yet, the latest plugin still shows beta36.  I'll test when I see v37 come through.
Thanks.

**Comment by rikvdkleij** [comment] 2018-12-17 09:56
@yunti beta37 is just approved by Jetbrains. Otherwise you can download the zip from the releases page.

Thanks!

**Comment by rikvdkleij** [comment] 2018-12-18 11:40
See #354

**Closed by rikvdkleij** 2018-12-18 11:40 UTC
