### ISSUE TITLE
Highlighting anomaly

### ISSUE THREAD

**Issue by Unisay** [rikvdkleij/intellij-haskell#188] opened 2017-05-25 15:18 UTC
**Actual behavior:**
  `\s0` is blue
  `\s` is black in the same position

**Expected behavior:**
   `\s0` is black 

**Screenshot:**

![screenshot at 17-13-25](https://cloud.githubusercontent.com/assets/1009751/26456536/9aa28442-416d-11e7-88f6-219fa2207910.png)

**Comment by rikvdkleij** [comment] 2017-07-17 08:50
Thanks for reporting.

I found the cause, it's a problem in the parser. I will fix it.

**Comment by rikvdkleij** [comment] 2017-08-07 08:18
Should be fixed in beta9.

**Closed** 2017-12-16 11:47 UTC
