### ISSUE TITLE
Syntax highliting error with missing space in list comprehension

### ISSUE THREAD

**Issue by Adrijaned** [rikvdkleij/intellij-haskell#528] opened 2020-03-24 11:07 UTC
When doing ![Screenshot_20200324_120446](https://user-images.githubusercontent.com/22203805/77418772-a907c680-6dc7-11ea-83c1-ae8800670efa.png)
, everything works as expected. However, if I for whatever reason miss the space in before the first pipe, this happens:
![Screenshot_20200324_120559](https://user-images.githubusercontent.com/22203805/77418952-eb310800-6dc7-11ea-98bb-5ccc7fd002ea.png)
Please note that the dark yellow continues until the very end of file, no matter what is after it.
Code compiles and behives as expected in both cases.

**Comment by rikvdkleij** [comment] 2020-03-24 17:08
Thanks for reporting!

Which version of the plugin?

**Comment by rikvdkleij** [comment] 2020-03-25 18:26
@Adrijaned Ok, I can reproduce this issue in latest beta.

**Comment by rikvdkleij** [comment] 2020-03-25 18:30
It's because the parser sees your second case as quasi quotation and that's right when the QuasiQuotes language extension is enabled...

**Comment by rikvdkleij** [comment] 2020-03-25 18:31
I don't know how to fix this issue.

**Comment by Adrijaned** [comment] 2020-03-25 22:39
Ooof, sorry for not getting to you earlier with the plugin version, only just got to PC. I'm only a beginner haskeller, but my quick google search revealed that quasiquotations have always the following syntax: `[ident|..|]`. Would it be possible to issue something like warning, prefferably at the line where the quasiquote is started, saying "A QuasiQuotation expression was started, but never ended", if the matching `|]` cannot be found until the end of file? An intent inserting the missing space for the warning along the lines of "Did you mean to write list comprehension?" would be appreciated too.

**Comment by rikvdkleij** [comment] 2020-03-26 06:25
> saying "A QuasiQuotation expression was started, but never ended

Yep, after some more digging, to get that behavior I have to move the quasi quotes element from the lexer to the bnf but that’s a risky change... but will try it.

**Comment by rikvdkleij** [comment] 2020-03-29 18:30
I don't succeed in finding a proper solution for this issue. Each alternative solution I found had  bigger issues than this issue.

@ice1000 Can you help?

**Comment by ice1000** [comment] 2020-03-30 00:32
Random guess: access language extensions in the lexer

**Comment by rikvdkleij** [comment] 2020-03-30 06:21
It’s not about language extensions, it’s about the quasi quote extension syntax which starts similar as a for comprehension. 
In don’t see a way in the QQ definition of the lexer to go back when there in no `|]` at the end.

**Comment by rikvdkleij** [comment] 2020-04-18 15:03
Should be fixed in beta69.

**Comment by rikvdkleij** [comment] 2020-05-24 19:12
Please reopen if still an issue.

**Closed by rikvdkleij** 2020-05-24 19:12 UTC
