### ISSUE TITLE
New project creation failing with intero build errors

### ISSUE THREAD

**Issue by aberent** [rikvdkleij/intellij-haskell#422] opened 2019-05-12 18:38 UTC

**Comment by aberent** [comment] 2019-05-12 18:53
Here is what should have been in the description:

I create a new, empty, project with a project SDK of  Haskell Stack Tool (1.9.3), and I get lots of error messages about problems with intero. See below. 

Once this happens I don't get the Haskell Error window, or error checking in the editor window.

12/05/19
19:35	Executing `/usr/local/bin/stack build intero` failed: /usr/local/bin/stack build intero:   
				Error: While constructing the build plan, the following exceptions were encountered:
				In the dependencies for intero-0.1.39:
				ghc-8.6.5 from stack configuration does not match >=7.8 && <=8.6.4  (latest matching version
				is 8.6.4)
				needed since intero is a build target.
				Some different approaches to resolving this:
				* Set 'allow-newer: true'
				in /home/anthony/.stack/config.yaml to ignore all version constraints and build anyway.
				* Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some
				working build configuration. This can be convenient when dealing with many complicated
				constraint errors, but results may be unpredictable.
				* Recommended action: try adding the following to your extra-deps
				in /home/anthony/haskell/htest/stack.yaml:
				ghc-8.6.4@sha256:628bc341218b5631136e015bdc6d2cf73f7888304554a1caaf659881672402fe
				Plan construction... (show balloon)

19:35	[global-stack-repl] Stack REPL could not be started within 30 seconds

19:35	[global-stack-repl] Executable named intero not found on path: ["/home/anthony/haskell/htest/.stack-work/install/x86_64-linux-tinfo6/lts-13.21/8.6.5/bin","/home/anthony/.stack/snapshots/x86_64-linux-tinfo6/lts-13.21/8.6.5/bin","/home/anthony/.stack/compiler-tools/x86_64-linux-tinfo6/ghc-8.6.5/bin","/home/anthony/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/bin","/home/anthony/.local/bin","/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games","/snap/bin"]

19:35	[project-stack-repl-htest:lib] Stack REPL could not be started within 30 seconds

19:35	[project-stack-repl-htest:lib] Executable named intero not found on path: ["/home/anthony/haskell/htest/.stack-work/install/x86_64-linux-tinfo6/lts-13.21/8.6.5/bin","/home/anthony/.stack/snapshots/x86_64-linux-tinfo6/lts-13.21/8.6.5/bin","/home/anthony/.stack/compiler-tools/x86_64-linux-tinfo6/ghc-8.6.5/bin","/home/anthony/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/bin","/home/anthony/.local/bin","/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games","/snap/bin"]

19:35	[global-stack-repl] Stack REPL could not be started within 30 seconds

19:35	[global-stack-repl] Executable named intero not found on path: ["/home/anthony/haskell/htest/.stack-work/install/x86_64-linux-tinfo6/lts-13.21/8.6.5/bin","/home/anthony/.stack/snapshots/x86_64-linux-tinfo6/lts-13.21/8.6.5/bin","/home/anthony/.stack/compiler-tools/x86_64-linux-tinfo6/ghc-8.6.5/bin","/home/anthony/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/bin","/home/anthony/.local/bin","/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin","/usr/games","/usr/local/games","/snap/bin"]

19:35	Hoogle database does not exist. Hoogle features can be optionally enabled by menu option `Tools`/`Haskell`/`(Re)Build Hoogle database`

**Comment by aberent** [comment] 2019-05-12 19:58
Now that I have investigated a bit more, it turns out that there is an easy workaround; change the resolver version in stack.yaml to lts-13.19 or earlier.

**Comment by TimoMeijer** [comment] 2019-05-12 21:37
The core of the issue is that intero does not allow for ghc-8.6.5 yet, which should be fixed soonTM

**Comment by develop7** [comment] 2019-05-15 13:05
Now that https://github.com/chrisdone/intero/pull/619 has been merged, we should be good to go.

**Comment by Eason0210** [comment] 2019-05-18 11:09
With the new release of intreo，it works well. Thanks @develop7

**Comment by TimoMeijer** [comment] 2019-05-19 12:48
For me it's still attempting to build intero-0.1.39, how would I get intellij-haskell to try and build intero-0.1.40?

**Comment by rikvdkleij** [comment] 2019-05-19 13:01
Try `stack update` in project's folder.

**Comment by rikvdkleij** [comment] 2019-05-23 20:16
Seems to be working now.

**Closed by rikvdkleij** 2019-05-23 20:16 UTC
