### ISSUE TITLE
Can't open files in non-Haskell directories anymore

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#200] opened 2017-08-09 21:36 UTC
As of 1.0.0-Beta9, I can't figure out how to open files that are outside of directories with Haskell packages. My repository has a lot of directories at the root, and only a few of them contain Haskell code. The directories that don't contain Haskell packages don't show up in the *Project* or *Project Files* views.

**Comment by rikvdkleij** [comment] 2017-08-10 08:25
I can not reproduce your issue.

For example, the `.stack-work` at the root of a project is visible. In the `Project view`, not in  Project Files` view (it's an ignored directory).

 Also other non-Haskell directories are visible, like `log` and `idea`. Those are visible in both views

**Comment by rikvdkleij** [comment] 2017-08-10 08:30
Maybe it helps to `synchronize` your root folder.

**Comment by chris-martin** [comment] 2017-08-11 23:07
My root folder doesn't show up in the `Project` view either. Perhaps it's relevant that I do not have a Haskell project in my root folder? There is a `stack.yaml` in the root, and multiple folders with Haskell projects in them.

**Comment by rikvdkleij** [comment] 2017-08-12 05:41
When you import existing Stack project to create new Haskell Stack IntelliJ project, you will have to select the folder which contains the `stack.yaml`.  Did you do that?

I have tested that with your example project from issue https://github.com/rikvdkleij/intellij-haskell/issues/180

**Comment by rikvdkleij** [comment] 2017-08-12 05:58
Okay, now I understand your problem :smile: 

When I create folder inside root folder of your example project, that folder does not show up. It looks a IntelliJ thing. I will try to find cause of the problem and if I can fix it.

**Comment by rikvdkleij** [comment] 2017-08-12 19:27
Did some investigation and I do not see a solution to solve this issue. It only shows folders if parent is inside module. Maybe it's an IntelliJ bug. 

I can not create Haskell module in case root folder does not contain Haskell package (Cabal file). Also creating some dummy model is not good solution because you will have to select SDK (Java, Static Web,..)

Workaround is to use the navigation bar. It allows you to navigate to folders inside the root folder.

**Comment by chris-martin** [comment] 2017-08-13 02:34
Could the Haskell plugin create a "dummy" module in the directory that contains the `stack.yaml` file?

**Comment by chris-martin** [comment] 2017-08-13 03:02
As a workaround, I've created a Java module at the root of the project.

**Comment by rikvdkleij** [comment] 2017-08-15 15:03
> Could the Haskell plugin create a "dummy" module in the directory that contains the stack.yaml file?

Yes, I will implement that.

**Comment by rikvdkleij** [comment] 2017-08-15 20:00
Created solution to solve this issue. To prevent name conflict with other Haskell modules, module name of empty parent module is name of project with added ` parent`. Please let me know if you know better name.

**Comment by rikvdkleij** [comment] 2017-08-20 09:51
Should be fixed in beta11

**Comment by rikvdkleij** [comment] 2017-10-10 18:44
@chris-martin  Improved the project structure for multi-package projects in beta12.

**Closed** 2017-12-16 11:48 UTC
