### ISSUE TITLE
Nested comments aren't parsed correctly

### ISSUE THREAD

**Issue by drathier** [rikvdkleij/intellij-haskell#249] opened 2018-01-05 01:06 UTC
This is parsed as a comment that ends at `nothing -}`.

```
{-| This represents a list of things between clear start and end delimiters.
Comments can appear before and after any item, or alone if there are no items.

For example:
  ( {- nothing -} )
  ( a, b )

TODO: this should be replaced with (Sequence a, Comments)
-}
```

**Comment by rikvdkleij** [comment] 2018-01-05 10:03
Thanks for reporting!

**Comment by rikvdkleij** [comment] 2018-12-17 20:21
Should be fixed in next beta.

**Comment by develop7** [comment] 2019-03-05 19:57
Couldn't reproduce in beta44

**Comment by rikvdkleij** [comment] 2019-05-22 13:28
Please reopen when it's still an issue.

**Closed by rikvdkleij** 2019-05-22 13:28 UTC
