### ISSUE TITLE
Popup window every time a file changes

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#197] opened 2017-08-05 23:05 UTC
Every time I type something in this project's `Main` module, I get a popup informing me that it's building. It makes the editor rather unusable. I can background the prompt each time, but it always comes right back up in the foreground next time.

Stack 1.5.0, IntelliJ 2017.2, IntelliJ-Haskell 1.0.0-beta9

![screenshot from 2017-08-05 19-03-48](https://user-images.githubusercontent.com/399718/28999342-e2905aaa-7a10-11e7-874a-81a1179ac4a0.png)

**Comment by maiermic** [comment] 2017-08-06 09:53
I have the same issue :disappointed: 

Linux, Stack 1.5.0, IntelliJ 2017.2.1, IntelliJ-Haskell 1.0.0-beta9

**Comment by rikvdkleij** [comment] 2017-08-06 10:57
Oops, it should only popup once if accompanying library is changed. I will fix it and release new version as quickly as possible. I have thoroughly tested the new version but missed this case apparently.

Point is that each target is loaded in it's own REPL since beta 9. So if library is changed and user navigates to file in executable, test or benchmark (from Cabal stanza) module, the library has to be rebuild.

**Comment by rikvdkleij** [comment] 2017-08-06 16:25
I found the cause. I also found another case which I did not take into account. This pam project is example of project in which one package has no library. It depends on library of another package in same project.

About the user experience. What do you think? If depending library is changed, should I always build starting with modal progress indicator in the foreground with option to put it in the background? Or always in the background. Currently it's starting in the foreground because I want the user to know that rebuild is happening and current compile state (annotations) could be stale.

**Comment by chris-martin** [comment] 2017-08-06 16:48
In my opinion, there's enough motion in the status bar at the bottom to indicate that a rebuild is happening, and it's usually better to err on the side of *not* doing anything that covers the main editor window.

**Comment by rikvdkleij** [comment] 2017-08-06 18:01
@chris-martin Okay, thanks for your opinion. I will do the rebuild completely in the background.

**Comment by rikvdkleij** [comment] 2017-08-06 20:42
I have uploaded beta10 to Jetbrains plugin repo. It can take some time before Jetbrains approves the update.

You can also download beta10 from https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta10 and install plugin from disk.

**Comment by rikvdkleij** [comment] 2017-08-07 14:22
Beta 10 is released. Should be fixed.

**Comment by maiermic** [comment] 2017-08-09 18:37
Thanks, it works fine :+1:

**Closed** 2017-08-09 21:28 UTC
